<table  border="0" cellpadding="5" cellspacing="0" width=100%>
<tr>
	<td align=center valign=middle>
<!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a href='http://www.liveinternet.ru/click' "+
"target=_blank><img src='http://counter.yadro.ru/hit?t15.2;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";h"+escape(document.title.substring(0,80))+";"+Math.random()+
"' alt='' title='LiveInternet: показано число просмотров за 24"+
" часа, посетителей за 24 часа и за сегодня' "+
"border=0 width=88 height=31><\/a>")//--></script><!--/LiveInternet-->
	</td>

	<td align=center valign=middle>
    <!-- Top.Elec.Ru Counter -->
<a href="http://www.elec.ru/" target=_blank><script language="JavaScript"><!--
ElNav = navigator; ElNavApp = ElNav.appName; ElDoc = document; ElDoc.cookie = "b=b";
ElCookie = ElDoc.cookie ? 1 : 0; ElNsc = (ElNavApp.substring(0, 2) == "Mi") ? 0 : 1;
ElScreen = screen; ElDepth = (ElNsc ==0 ) ? ElScreen.colorDepth : ElScreen.pixelDepth;
document.write('<img src="http://top.elec.ru/cnt?' + 
'id=12078&sc=35&' + 
'scr=' + ElScreen.width + 'x' + ElScreen.height + 'x' + ElDepth + '&' +
'cookie=' + ElCookie + '&' +
'ref=' + escape(ElDoc.referrer) + '&' + 
'r=' + Math.random() + '" ' +
'width="88" height="31" border="0" alt="Top.Elec.Ru - Рейтинг и каталог электротехнических ресурсов">');
// --></script><noscript><img src="http://top.elec.ru/cnt?id=12078&sc=35" 
width="88" height="31" border="0" alt="Top.Elec.Ru - Рейтинг и каталог электротехнических ресурсов"></noscript></a>
<!-- Top.Elec.Ru Counter -->

	</td>
 </tr>
 <tr>
    <td align=center valign=middle>
<!-- begin of Top100 code -->

<script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?2305832"></script>
<noscript>
<a href="http://top100.rambler.ru/navi/2305832/">
<img src="http://counter.rambler.ru/top100.cnt?2305832" alt="Rambler's Top100" border="0" />
</a>

</noscript>
<!-- end of Top100 code -->
    </td>
    <td align=center valign=middle>
    <!--RASKRYTKA.RU counter-->
<a href="http://www.raskrytka.ru/" target="_blank"><img src="http://counter.web-marketolog.ru/counter/?mode=b1-7" width="88" height="31" border=0 alt="раскрутка сайта в поисковиках, раскрутка сайтов в москве"></a>
<!--/RASKRYTKA.RU counter -->
    
    <!-- Yandex.Metrika counter -->
    <div style="display:none;"><script type="text/javascript">
    (function(w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter6896539 = new Ya.Metrika({id:6896539,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true,
                        webvisor:true});
            }
            catch(e) { }
        });
    })(window, 'yandex_metrika_callbacks');
    </script></div>
    <script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script>
    <noscript><div><img src="//mc.yandex.ru/watch/6896539" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->    
    </td>
</tr>
</table>