<? //require_once("inc/script/html_script.inc"); ?>

<link rel="stylesheet" type="text/css" href="/style_bb.css">
<script type="text/javascript" src="/inc/js/forum.js"></script>
<script type="text/javascript" src="/inc/lib/bbcode/xbb.js.php"></script>
<script type="text/javascript">
XBB.path = '/inc/lib/bbcode'; // путь к либе
XBB.textarea_id = 'content_bb'; // идентификатор textarea
XBB.area_width = '630px'; // ширина окошка редактора
XBB.area_height = '400px'; // высота окошка редактора
XBB.state = 'plain'; // 'plain' or 'highlight'
// Одна из следующих строк должна быть раскомменчена
//XBB.lang = 'ru_utf8'; // русская локаль UTF-8
XBB.lang = 'ru_cp1251'; // русская локаль windows-1251
</script>

